[programs.devnet]
solana_gif_backend = "GeHAw8bNJPRVqtyDhfQ4UjACTRw8fHjdDBnpMpFZ9sQK"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/saurabhsrivastava/.config/solana/id.json"

[scripts]
# test = "mocha -t 1000000 tests/"
test = "node tests/solana-gif-backend.js"
